version: '3'

services:
  database:
    image: postgres:12.1-alpine
    container_name: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=admin
    restart: on-failure
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - database
    networks:
      - app-network

  front:
    build:
      context: pong/static/
      dockerfile: dockerfile
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    ports:
      - 1234:1234
    volumes:
      - .:/code
    depends_on:
      - django
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
