"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ENV_FILE=str(Path(BASE_DIR)) + '/auth.env'
# myvars = dotenv_values(ENV_FILE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*_=1g=ofwsw@=c!zzem-^5sj_=xy%frbhe0eq)q&8xe!)=a@%j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

LOGIN_URL = '/login'
# Application definition

INSTALLED_APPS = [
	'daphne', #added for pong game
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', #added for REST api
    'rest_framework.authtoken',
	'github', #added for github login
	'ludo', #added for game
	'nopassauth', #added for 42 login
	'pong', #added for pong game
	'corsheaders', #added for pong game
]

ASGI_APPLICATION = 'main.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
# CHANNEL_LAYERS = {
# 	'default': {
# 		'BACKEND':'channels.layers.InMemoryChannelLayer'
# 	}
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware', #added for pong game
    'django.middleware.common.CommonMiddleware',
	# 'pong.middleware.PortRedirectMiddleware', #added for pong game
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
	
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('main/templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_ROOT = 'staticfiles'
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "main/static",
    "ludo/static/",
    "pong/templates/static/",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# GITHUB OAUTH
GITHUB_OAUTH_CLIENT_ID = 'a8e03103754833456ade'
GITHUB_OAUTH_SECRET = '06860f9b942c9a2f14a59ce188bce560a46db4bb'
GITHUB_OAUTH_CALLBACK_URL = 'http://127.0.0.1:8000/git/callback'
GITHUB_OAUTH_SCOPES = []

# 42AUTH
OAUTH42_CLIENT_ID = 'u-s4t2ud-c2123d6752521e96e8bbd0c748a04b0739c0885bb724efbc8ef78cfcb464d05e'
OAUTH42_SECRET = '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'
OAUTH42_CALLBACK_URL = 'http://127.0.0.1:8000/callback/'
OAUTH42_SCOPES = []
