# Generated by Django 4.2.11 on 2024-03-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nopassauth', '0002_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('result_user1', models.IntegerField()),
                ('result_user2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('winrate', models.FloatField(default=0)),
                ('score', models.IntegerField(default=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='matches',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ludo_games_played',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pong_games_played',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score',
        ),
        migrations.AddField(
            model_name='stats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='nopassauth.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='players', to='nopassauth.match'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stats',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nopassauth.stats'),
        ),
    ]
