# Generated by Django 4.2.11 on 2024-03-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopassauth', '0003_match_stats_delete_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
